spring:
  datasource:
    hikari:
      jdbc-url: "jdbc:postgresql://localhost:5432/proj_manager_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
      maximum-pool-size: 10
      driver-class-name: org.postgresql.Driver
    username: postgres
    password: 1111
    url: "jdbc:postgresql://localhost:5432/proj_manager_db?useUnicode=true&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=UTC"
    driver-class-name: org.postgresql.Driver
  mail:
    protocol: smtp
    properties.mail.smtp:
      auth: true
      starttls.enable: true
    host: smtp.gmail.com
    port: 587
    username: 1111@gmail.com
    password: 1111
---

jwtconfig:
  secret: mySecret
  expiration: 60000000

---
